# CMake generated Testfile for 
# Source directory: /workspace/test
# Build directory: /workspace/build-test/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_backend_franja_horaria]=] "/workspace/build-test/test/test_backend_franja_horaria")
set_tests_properties([=[test_backend_franja_horaria]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;55;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_backend_aula]=] "/workspace/build-test/test/test_backend_aula")
set_tests_properties([=[test_backend_aula]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;60;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_backend_materia]=] "/workspace/build-test/test/test_backend_materia")
set_tests_properties([=[test_backend_materia]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;65;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_backend_profesor]=] "/workspace/build-test/test/test_backend_profesor")
set_tests_properties([=[test_backend_profesor]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;70;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_backend_horario]=] "/workspace/build-test/test/test_backend_horario")
set_tests_properties([=[test_backend_horario]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;75;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_backend_plan_estudio]=] "/workspace/build-test/test/test_backend_plan_estudio")
set_tests_properties([=[test_backend_plan_estudio]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;80;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_backend_output_schedule]=] "/workspace/build-test/test/test_backend_output_schedule")
set_tests_properties([=[test_backend_output_schedule]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;85;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_backend_database]=] "/workspace/build-test/test/test_backend_database")
set_tests_properties([=[test_backend_database]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;90;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_backend_entity_graph]=] "/workspace/build-test/test/test_backend_entity_graph")
set_tests_properties([=[test_backend_entity_graph]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;96;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_middleware_health_check]=] "/workspace/build-test/test/test_middleware_health_check")
set_tests_properties([=[test_middleware_health_check]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;105;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_servicio_aula]=] "/workspace/build-test/test/test_servicio_aula")
set_tests_properties([=[test_servicio_aula]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;119;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_servicio_materias]=] "/workspace/build-test/test/test_servicio_materias")
set_tests_properties([=[test_servicio_materias]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;125;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_servicio_planes_estudio]=] "/workspace/build-test/test/test_servicio_planes_estudio")
set_tests_properties([=[test_servicio_planes_estudio]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;131;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_servicio_carga_horaria]=] "/workspace/build-test/test/test_servicio_carga_horaria")
set_tests_properties([=[test_servicio_carga_horaria]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;137;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_composicion_plan]=] "/workspace/build-test/test/test_composicion_plan")
set_tests_properties([=[test_composicion_plan]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;143;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_servicio_consulta_horario]=] "/workspace/build-test/test/test_servicio_consulta_horario")
set_tests_properties([=[test_servicio_consulta_horario]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;149;add_qtest;/workspace/test/CMakeLists.txt;0;")
add_test([=[test_servicio_horario_salida]=] "/workspace/build-test/test/test_servicio_horario_salida")
set_tests_properties([=[test_servicio_horario_salida]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/test/CMakeLists.txt;33;add_test;/workspace/test/CMakeLists.txt;154;add_qtest;/workspace/test/CMakeLists.txt;0;")
