// This file is autogenerated. Changes will be overwritten.
#include "GYHPFG4CL2/moc_teacher_form_dialog.cpp"
#include "UVLADIE3JM/moc_logindialog.cpp"
#include "Z3L7HTGYLD/moc_dashboard_widget.cpp"
#include "Z3L7HTGYLD/moc_main_window.cpp"
#include "Z3L7HTGYLD/moc_teacher_list_widget.cpp"
#include "Z3L7HTGYLD/moc_view_placeholder.cpp"
